In [1]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
import random
from pathlib import Path
import os 
import sys
from collections import Counter
from imblearn.under_sampling import RandomUnderSampler

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
BASE_DIR = Path.cwd() 
print(BASE_DIR)

c:\Users\Neezy\Videos\attacks_improved_v2\Attacks-Improved_v2\Random_forest

In [4]:
project_root = os.path.abspath('..')
if project_root not in sys.path: 
    sys.path.append(project_root)

In [5]:
data = pd.read_csv(BASE_DIR.parent/'data/ds_with_sample_name.csv')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [6]:
# import attacks
from attack_functionality.functionality_preserving_attack import FunctionalityPreservingAttack 
attack = FunctionalityPreservingAttack()

In [7]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [8]:
random_under_sample = RandomUnderSampler(random_state=42)

In [9]:
x_resample, y_resample = random_under_sample.fit_resample(X,y)
balanced_df = pd.DataFrame(x_resample, columns=X.columns)
balanced_df['label'] = y_resample

C:\Users\Neezy\AppData\Local\Temp\ipykernel_13352\380394481.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  balanced_df['label'] = y_resample

In [10]:
balanced_df = balanced_df.copy()

In [11]:
balanced_df['label'].value_counts()

label
0    570
1    570
Name: count, dtype: int64

In [12]:
balanced_df.head()

,Sample Name,category,SetErrorMode,OleInitialize,LdrGetDllHandle,LdrLoadDll,LdrGetProcedureAddress,NtOpenSection,NtMapViewOfSection,RegOpenKeyExW,RegQueryValueExW,RegCloseKey,NtClose,NtOpenKey,NtQueryValueKey,GetSystemWindowsDirectoryW,NtCreateFile,NtCreateSection,RegOpenKeyExA,CreateActCtxW,GetSystemDirectoryW,GetVolumeNameForVolumeMountPointW,NtDuplicateObject,LoadStringW,NtCreateMutant,GetNativeSystemInfo,RegEnumKeyW,NtQuerySystemInformation,RegQueryValueExA,NtQueryDirectoryFile,GlobalMemoryStatusEx,CoCreateInstance,NtAllocateVirtualMemory,CreateDirectoryW,DeleteFileW,GetFileSizeEx,NtReadFile,GetFileInformationByHandleEx,GetSystemTimeAsFileTime,GetVolumePathNamesForVolumeNameW,LdrUnloadDll,CoInitializeEx,NtOpenProcess,CoUninitialize,NtFreeVirtualMemory,NtOpenFile,NtQueryInformationFile,GetFileAttributesW,FindFirstFileExW,NtQueryAttributesFile,NtUnmapViewOfSection,SetFilePointerEx,SetFilePointer,GetTempPathW,GetFileSize,NtWriteFile,FindResourceExW,LoadResource,SHGetFolderPathW,NtProtectVirtualMemory,GetFileType,ReadProcessMemory,GetForegroundWindow,GetSystemMetrics,SetFileTime,NtSetInformationFile,SearchPathW,NtOpenMutant,RegEnumKeyExW,DrawTextExW,GetAsyncKeyState,GetDiskFreeSpaceExW,GetKeyState,FindWindowW,FindWindowExA,CreateThread,MoveFileWithProgressW,SetFileAttributesW,RemoveDirectoryW,NtTerminateProcess,CreateToolhelp32Snapshot,Process32FirstW,Process32NextW,FindWindowExW,SetEndOfFile,GetCursorPos,SetUnhandledExceptionFilter,OutputDebugStringA,GetSystemInfo,FindResourceW,SizeofResource,NtDelayExecution,GetKeyboardState,WSAStartup,socket,setsockopt,NtDeviceIoControlFile,closesocket,GetBestInterfaceEx,GetAdaptersAddresses,NtQueryKey,RegCreateKeyExW,GetAddrInfoW,GetUserNameExW,RegSetValueExW,RegDeleteValueW,InternetQueryOptionA,URLDownloadToFileW,IsDebuggerPresent,CreateProcessInternalW,GetTimeZoneInformation,LookupAccountSidW,SendNotifyMessageW,UuidCreate,GetFileVersionInfoSizeW,GetFileVersionInfoW,NtEnumerateValueKey,EnumWindows,OpenSCManagerW,GetComputerNameW,GetUserNameW,NetShareEnum,GetFileInformationByHandle,DeviceIoControl,ShellExecuteExW,RegQueryInfoKeyW,RegEnumValueW,RegDeleteKeyW,NtReadVirtualMemory,NtOpenKeyEx,NtSetValueKey,NtCreateKey,GetVolumePathNameW,GetFileAttributesExW,GetUserNameExA,RegCreateKeyExA,CryptAcquireContextW,NtEnumerateKey,NtDeleteKey,OpenServiceW,NtOpenDirectoryObject,CreateJobObjectW,SetInformationJobObject,RegEnumKeyExA,GetShortPathNameW,LoadStringA,FindResourceA,DrawTextExA,RegQueryInfoKeyA,RegSetValueExA,SHGetSpecialFolderLocation,NtCreateThreadEx,NtResumeThread,gethostbyname,GetSystemDirectoryA,FindResourceExA,GetDiskFreeSpaceW,CertOpenStore,CryptDecodeObjectEx,CertControlStore,CryptHashData,NtOpenThread,MessageBoxTimeoutW,LookupPrivilegeValueW,CryptAcquireContextA,SetFileInformationByHandle,RemoveDirectoryA,SetWindowsHookExW,CopyFileW,GetFileVersionInfoSizeExW,GetFileVersionInfoExW,CoInitializeSecurity,WSASocketW,WSAConnect,UnhookWindowsHookEx,CertOpenSystemStoreW,getaddrinfo,InternetCrackUrlW,CoCreateInstanceEx,CoGetClassObject,IWbemServices_ExecQuery,SetStdHandle,GlobalMemoryStatus,NetGetJoinInformation,CryptCreateHash,GetComputerNameA,InternetOpenA,InternetOpenUrlA,InternetCloseHandle,ReadCabinetState,InternetOpenW,InternetConnectW,HttpOpenRequestW,HttpSendRequestW,NtDeleteValueKey,HttpQueryInfoA,RegEnumValueA,CryptProtectMemory,CreateServiceW,WriteConsoleA,CopyFileA,WriteProcessMemory,SendNotifyMessageA,RegDeleteKeyA,WriteConsoleW,JsGlobalObjectDefaultEvalHelper,ObtainUserAgentString,StartServiceW,NtQueueApcThread,RtlAddVectoredContinueHandler,CryptExportKey,CryptGenKey,CryptEncrypt,NetUserGetInfo,GetUserNameA,InternetOpenUrlW,GetAdaptersInfo,Module32FirstW,NtGetContextThread,Module32NextW,RtlAddVectoredExceptionHandler,NtSuspendThread,OpenSCManagerA,OpenServiceA,NtQueryMultipleValueKey,MessageBoxTimeoutA,ControlService,NtTerminateThread,EncryptMessage,DecryptMessage,DeleteService,FindWindowA,RtlRemoveVectoredExceptionHandler,ioctlsocket,connect,select,SetWindowsHookExA,CreateServiceA,bind,listen,getsockname,accept,InternetCrackUrlA,InternetConnectA,HttpOpenRequestA,HttpSendRequestA,sendto,shutdown,RtlDecompressBuffer,NtSetContextThread,Thread32First,Thread32Next,CreateRemoteThread,InternetReadFile,CreateRemoteThreadEx,timeGetTime,DnsQuery_A,InternetGetConnectedState,RegisterHotKey,CryptDecrypt,CopyFileExW,NtDeleteFile,send,DeleteUrlCacheEntryA,EnumServicesStatusW,recv,NtWriteVirtualMemory,InternetSetOptionA,NtLoadDriver,EnumServicesStatusA,RegDeleteValueA,CertCreateCertificateContext,InternetSetStatusCallback,IWbemServices_ExecMethod,AssignProcessToJobObject,StartServiceA,CryptProtectData,CryptUnprotectData,CryptUnprotectMemory,label
96,Database_Q-Eye Portable.exe,Development,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
97,Database_DB Browser for SQLite Portable.exe,Development,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
99,Database_Database Browser Portable.exe,Development,9,2,209,49,322,10,17,714,2343,579,360,39,12,7,237,11,7,1,16,4,5,8,3,1,111,1,1,112,1,7,503,122,8,12,1994,12,83,8,9,17,14,20,581,16,8,318,48,3,19,1,79,1,4,1517,18,16,2,2,0,0,2,1557,34,5,3,3,192,127,0,4,48,1,2,1,0,7,1,3,1,1,34,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
100,Action Games_AssaultCube Portable.exe,Games,9,2,48,40,150,10,16,709,2339,574,2864,39,12,7,2023,10,7,1,3,4,5,8,3,1,111,3,1,112,1,7,444,5900,10,12,12375,12,82,8,11,17,48,20,287,592,166,9267,74,2,18,1,4551,1,4,9313,18,16,1,2,3,155,3,3087,1895,37,3,3,192,169,1,4,48,1,2,1,2,8,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
101,Astronomy_Stellarium Portable.exe,Education,9,2,195,53,319,12,19,890,2407,752,3875,42,12,7,3607,11,7,2,16,4,5,8,3,1,111,1,1,112,1,7,439,1121,9,12,54610,12,83,8,10,18,14,21,207,114,8,7970,60,3,22,1,7809,1,4,47827,27,25,2,2,0,0,6,12329,3413,5,3,3,358,294,0,4,48,1,2,1,1,9,2,3,1,1,32,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [13]:
features = ['Sample Name', 'category', 'LdrGetProcedureAddress', 'GetSystemInfo', 'GetNativeSystemInfo', 'NtQuerySystemInformation',  'CreateToolhelp32Snapshot', 'Process32FirstW', 'RegOpenKeyExW', 'RegQueryValueExW',
            'RegCloseKey', 'NtCreateFile', 'GetDiskFreeSpaceW', 'CryptAcquireContextW', 'CryptGenKey', 
            'CryptExportKey', 'RegCreateKeyExW', 'RegSetValueExW', 'CreateThread', 'FindFirstFileExW',
            'NtWriteFile', 'ShellExecuteExW', 'InternetOpenW', 
            'InternetConnectW', 'HttpOpenRequestW', 'InternetReadFile', 'InternetOpenUrlA', 
            'InternetCloseHandle']

In [14]:
benign_features = ['LdrGetDllHandle',
 'RegOpenKeyExW',
 'RegQueryValueExW',
 'RegCloseKey',
 'GetSystemWindowsDirectoryW',
 'CreateActCtxW',
 'GetSystemDirectoryW',
 'GetVolumeNameForVolumeMountPointW',
 'RegEnumKeyW',
 'GlobalMemoryStatusEx',
 'CreateDirectoryW',
 'GetVolumePathNamesForVolumeNameW',
 'LdrUnloadDll',
 'GetFileAttributesW',
 'SHGetFolderPathW',
 'GetSystemMetrics',
 'SetFileTime',
 'RegEnumKeyExW',
 'DrawTextExW',
 'FindWindowW',
 'FindWindowExA',
 'RemoveDirectoryW',
 'GetKeyboardState',
 'SendNotifyMessageW',
 'GetFileVersionInfoSizeW',
 'EnumWindows',
 'GetUserNameExA',
 'RegCreateKeyExA',
 'SetInformationJobObject',
 'DrawTextExA',
 'RegSetValueExA',
 'SHGetSpecialFolderLocation',
 'gethostbyname',
 'CertOpenStore',
 'CertControlStore',
 'SetWindowsHookExW',
 'WSASocketW',
 'WSAConnect',
 'UnhookWindowsHookEx',
 'CertOpenSystemStoreW',
 'HttpQueryInfoA',
 'CryptProtectMemory',
 'WriteProcessMemory',
 'SendNotifyMessageA',
 'JsGlobalObjectDefaultEvalHelper',
 'ObtainUserAgentString',
 'label'
 ]

In [15]:
benign_filtered = [item for item in benign_features if item not in features]

In [16]:
len(benign_filtered)

44

In [17]:
functionality_features = features.extend(benign_filtered)

In [18]:
print(len(features))

72

In [19]:
df = balanced_df[features]

In [20]:
df.head()

,Sample Name,category,LdrGetProcedureAddress,GetSystemInfo,GetNativeSystemInfo,NtQuerySystemInformation,CreateToolhelp32Snapshot,Process32FirstW,RegOpenKeyExW,RegQueryValueExW,RegCloseKey,NtCreateFile,GetDiskFreeSpaceW,CryptAcquireContextW,CryptGenKey,CryptExportKey,RegCreateKeyExW,RegSetValueExW,CreateThread,FindFirstFileExW,NtWriteFile,ShellExecuteExW,InternetOpenW,InternetConnectW,HttpOpenRequestW,InternetReadFile,InternetOpenUrlA,InternetCloseHandle,LdrGetDllHandle,GetSystemWindowsDirectoryW,CreateActCtxW,GetSystemDirectoryW,GetVolumeNameForVolumeMountPointW,RegEnumKeyW,GlobalMemoryStatusEx,CreateDirectoryW,GetVolumePathNamesForVolumeNameW,LdrUnloadDll,GetFileAttributesW,SHGetFolderPathW,GetSystemMetrics,SetFileTime,RegEnumKeyExW,DrawTextExW,FindWindowW,FindWindowExA,RemoveDirectoryW,GetKeyboardState,SendNotifyMessageW,GetFileVersionInfoSizeW,EnumWindows,GetUserNameExA,RegCreateKeyExA,SetInformationJobObject,DrawTextExA,RegSetValueExA,SHGetSpecialFolderLocation,gethostbyname,CertOpenStore,CertControlStore,SetWindowsHookExW,WSASocketW,WSAConnect,UnhookWindowsHookEx,CertOpenSystemStoreW,HttpQueryInfoA,CryptProtectMemory,WriteProcessMemory,SendNotifyMessageA,JsGlobalObjectDefaultEvalHelper,ObtainUserAgentString,label
96,Database_Q-Eye Portable.exe,Development,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
97,Database_DB Browser for SQLite Portable.exe,Development,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
99,Database_Database Browser Portable.exe,Development,322,0,1,1,1,1,714,2343,579,237,0,0,0,0,0,0,1,48,1517,0,0,0,0,0,0,0,209,7,1,16,4,111,1,122,8,9,318,2,1557,34,192,127,1,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
100,Action Games_AssaultCube Portable.exe,Games,150,0,1,3,0,0,709,2339,574,2023,0,0,0,0,0,0,1,74,9313,0,0,0,0,0,0,0,48,7,1,3,4,111,1,5900,8,11,9267,1,3087,1895,192,169,1,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
101,Astronomy_Stellarium Portable.exe,Education,319,0,1,1,1,1,890,2407,752,3607,0,0,0,0,0,0,1,60,47827,0,0,0,0,0,0,0,195,7,2,16,4,111,1,1121,8,10,7970,2,12329,3413,358,294,1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [21]:
X_bal = df.iloc[:, 2:-1].values
y_bal = df.iloc[:,-1].values
original_indices = np.arange(len(X_bal)) 
X_train, X_test, y_train, y_test, idx_train, idx_test = train_test_split(X_bal, y_bal, original_indices, test_size=0.2, random_state=42)
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n {cm}") 
cr = classification_report(y_test, y_pred)
print(f"Classification report:\n {cr}")

Accuracy: 94.30%
Confusion Matrix:
 [[125   3]
 [ 10  90]]
Classification report:
               precision    recall  f1-score   support

           0       0.93      0.98      0.95       128
           1       0.97      0.90      0.93       100

    accuracy                           0.94       228
   macro avg       0.95      0.94      0.94       228
weighted avg       0.94      0.94      0.94       228

In [22]:
def make_pred(sample): 
    single_pred = classifier.predict([sample])
    return single_pred

In [23]:
xtrain_candidate_num = round(0.2*len(X_train))
print(xtrain_candidate_num)

182

In [24]:
ransomware_training_sample_indices = np.where(y_train==1)[0]
non_zero_mask = X_train[ransomware_training_sample_indices].sum(axis=1) !=0
valid_indices = ransomware_training_sample_indices[non_zero_mask]

idx = np.random.choice(valid_indices, 182, replace=False)
xtrain_poison_candidates = X_train[idx]

In [25]:
print(len(xtrain_poison_candidates))

182

In [26]:
perturbation=20
asamples, adv_idx = attack.generate_adversarial_sample(features, idx, xtrain_poison_candidates, perturbation, classifier)

["Feature: CreateDirectoryW changed: {'from': 0, 'to': 1}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: RegEnumKeyExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: EnumWindows changed: {'from': 0, 'to': 3}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: LdrUnloadDll changed: {'from': 0, 'to': 6}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 1}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: RegEnumKeyExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: RegEnumKeyExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 1}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 17}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 4}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: SetFileTime changed: {'from': 0, 'to': 15}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 5}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: gethostbyname changed: {'from': 0, 'to': 18}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateDirectoryW changed: {'from': 0, 'to': 1}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 1}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: RegEnumKeyExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 1}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 17}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: RegEnumKeyExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: DrawTextExW changed: {'from': 0, 'to': 1}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: RegEnumKeyExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 12}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 20}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]
["Feature: RegEnumKeyW changed: {'from': 0, 'to': 3}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 6}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 1}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 17}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: CreateActCtxW changed: {'from': 0, 'to': 4}", "Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 8}", "Feature: SetFileTime changed: {'from': 0, 'to': 12}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: DrawTextExW changed: {'from': 0, 'to': 2}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 20}", "Feature: GetKeyboardState changed: {'from': 0, 'to': 5}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 16}", "Feature: DrawTextExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 4}", "Feature: gethostbyname changed: {'from': 0, 'to': 17}", "Feature: CertOpenStore changed: {'from': 0, 'to': 2}"]
["Feature: GlobalMemoryStatusEx changed: {'from': 0, 'to': 7}", "Feature: CreateDirectoryW changed: {'from': 0, 'to': 8}", "Feature: LdrUnloadDll changed: {'from': 0, 'to': 5}", "Feature: SHGetFolderPathW changed: {'from': 0, 'to': 4}", "Feature: SetFileTime changed: {'from': 0, 'to': 13}", "Feature: RegEnumKeyExW changed: {'from': 0, 'to': 3}", "Feature: FindWindowW changed: {'from': 0, 'to': 2}", "Feature: FindWindowExA changed: {'from': 0, 'to': 11}", "Feature: RemoveDirectoryW changed: {'from': 0, 'to': 17}", "Feature: SendNotifyMessageW changed: {'from': 0, 'to': 18}", "Feature: RegSetValueExA changed: {'from': 0, 'to': 5}", "Feature: SHGetSpecialFolderLocation changed: {'from': 0, 'to': 3}", "Feature: gethostbyname changed: {'from': 0, 'to': 12}", "Feature: CertOpenStore changed: {'from': 0, 'to': 3}"]

In [27]:
np.save("rf_adversarial_samples_bal_functionality_preserving.npy", np.array(asamples))

In [28]:
print(len(asamples))
print(f"AGR: {len(asamples)/len(xtrain_poison_candidates):.4f}")

170
AGR: 0.9341

In [29]:
### Adversarial Retrain ###  
mask = np.ones(X_train.shape[0], dtype=bool)
mask[adv_idx] = False

X_train_base_samples_removed = X_train[mask]
y_train_base_samples_removed = y_train[mask]
print(f"length of Xtrain before successful base adversarial samples removed: {len(X_train)}")
print(f"length of Xtrain with successful base adversarial samples removed: {len(X_train_base_samples_removed)}")

### Select a hold out test set of the generated adversarial samples
k = round(0.2 * len(asamples)) 
print(f"20% of the adversarial samples held out for testing: {k}")
remove_samples_from_asamples = random.sample(asamples, k)
print(len(remove_samples_from_asamples))

### remove test set from total adversarial samples and add adversarial samples to the training set 
result = [item for item in asamples if item not in remove_samples_from_asamples]
np_result = np.array(result)
print(len(result))
poisoned_xtrain = np.concatenate((X_train_base_samples_removed, np_result))
print(f"Total length of poisoned Xtrain: {len(poisoned_xtrain)}")

### Add the corresponding amount of ytrain adversarial samples. (correctly labelled as ransomware) 
adv_y = []
for i in range(len(np_result)): 
    adv_y.append(1) 
    
print(len(adv_y))

np_advy = np.array(adv_y)
poisoned_ytrain = np.concatenate((y_train_base_samples_removed, np_advy))
print(f"Total length of poisoned Ytrain: {len(poisoned_ytrain)}") 

if len(poisoned_ytrain) == len(poisoned_xtrain): 
    print("Poisoned Xtrain and ytrain are aligned, posioned training can now commence")
else: 
    print("Not aligned, something is not aligned, check k value")

length of Xtrain before successful base adversarial samples removed: 912
length of Xtrain with successful base adversarial samples removed: 742
20% of the adversarial samples held out for testing: 34
34
96
Total length of poisoned Xtrain: 838
96
Total length of poisoned Ytrain: 838
Poisoned Xtrain and ytrain are aligned, posioned training can now commence

In [30]:
poisoned_classifier = RandomForestClassifier(random_state=42)
poisoned_classifier.fit(poisoned_xtrain, poisoned_ytrain)
y_pred_poisoned = poisoned_classifier.predict(X_test)
poisoned_accuracy = accuracy_score(y_test, y_pred_poisoned)
print(f'Accuracy trained on poisoned samples: {poisoned_accuracy * 100:.2f}%')
cm_poisoned = confusion_matrix(y_test, y_pred_poisoned)
print(f"Confusion Matrix trained on poisoned samples:\n {cm_poisoned}") 
cr_poisoned = classification_report(y_test, y_pred_poisoned)
print(f"Classification report trained on poisoned samples:\n {cr_poisoned}")

Accuracy trained on poisoned samples: 94.74%
Confusion Matrix trained on poisoned samples:
 [[126   2]
 [ 10  90]]
Classification report trained on poisoned samples:
               precision    recall  f1-score   support

           0       0.93      0.98      0.95       128
           1       0.98      0.90      0.94       100

    accuracy                           0.95       228
   macro avg       0.95      0.94      0.95       228
weighted avg       0.95      0.95      0.95       228

In [31]:
def make_pred_poisoned(samples):
    predictions = [] 
    for sample in samples:
        single_pred = poisoned_classifier.predict([sample])
        predictions.append(single_pred)
        print(single_pred) 
        if single_pred[0] == 1: 
            print("Correctly identified adversarial ransomware sample") 
        else: 
            print("Adversarial sample still adversarial")

    zero_counter = 0 
    one_counter = 0 
    for pred in predictions:
        if pred != 1: 
            zero_counter +=1 
        else:
            one_counter+=1 
        
    
    print(f"Samples still adversarial: {zero_counter}")
    print(f"adversarial_samples identified: {one_counter}")

make_pred_poisoned(remove_samples_from_asamples)

[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
[1]
Correctly identified adversarial ransomware sample
Samples still adversarial: 0
adversarial_samples identified: 34

In [32]:
###Model transfer ###
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [33]:
### Target Models ####
##  Trained on original data
#   No adversarial samples are added to the training data 

### Random Forest ####
classifier_dt = DecisionTreeClassifier(random_state=42)
classifier_dt.fit(X_train, y_train)
y_pred_rf = classifier_dt.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf) 
print(f"Accuracy of DT Target Model: {accuracy_score(y_test, y_pred):.2f}")

### XGboost #### 
params = {
    'objective':'binary:logistic',
    'max_depth':4,
    'learning_rate':0.1,
    'n_estimators':100,
    'alpha':10
}

model = XGBClassifier(**params)
model.fit(X_train, y_train)
y_pred_xgb = model.predict(X_test)
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
print(f'Accuracy of the XGboost Model: {accuracy_xgb * 100:.2f}%') 

### SVM Classifier Kernel=Poly ###
svm_classifier = SVC(kernel='poly', C=4.0, random_state=42)
svm_classifier.fit(X_train, y_train)
y_pred_svm = svm_classifier.predict(X_test)
print(f"Accuracy of the SVM Classifier (Kernel=Poly): {accuracy_score(y_test, y_pred_svm):.2f}")

## SVM Classifier Kernel=Linear ###
svm_classifier_linear = SVC(kernel='linear', C=4.0, random_state=42)
svm_classifier_linear.fit(X_train, y_train)
y_pred_svm_linear = svm_classifier_linear.predict(X_test)
print(f"Accuracy of the SVM Classifier (Kernel=Linear) : {accuracy_score(y_test, y_pred_svm_linear):.2f}")

### Logistic Regression ###
LR_model = LogisticRegression(solver='saga',max_iter=5000)
LR_model.fit(X_train, y_train)
ypred_LR = LR_model.predict(X_test)
accuracy = accuracy_score(y_test, ypred_LR)
print(f"accuracy of the Logistic Regression Model: {round(accuracy,2)}")

Accuracy of DT Target Model: 0.94
Accuracy of the XGboost Model: 92.11%
Accuracy of the SVM Classifier (Kernel=Poly): 0.47
Accuracy of the SVM Classifier (Kernel=Linear) : 0.91
accuracy of the Logistic Regression Model: 0.83

c:\Users\Neezy\anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [34]:
def evasion_attack(adversarial_samples,
                   DT_Model,
                   XGB_Model, 
                   SVM_poly_model, 
                   SVM_Linear,
                   Logistic_reg_model):
    
    predictions = {
        "Decision_Tree":[],
        "XGB":[],
        "SVM_poly": [], 
        "SVM_Linear":[], 
        "Logistic_Regression":[]   
    }
    
    models = {
        "Decision_Tree": DT_Model,
        "XGB":XGB_Model,
        "SVM_poly": SVM_poly_model,
        "SVM_Linear":SVM_Linear, 
        "Logistic_Regression":Logistic_reg_model
    }
    
    for name, model in models.items():
        preds = model.predict(adversarial_samples)
        predictions[name] = preds.tolist()
            
    
    return predictions

In [35]:
res = evasion_attack(asamples, classifier_dt, model, svm_classifier, svm_classifier_linear, LR_model)
evaded_ids=[]
evaded_samples = []
original_positions = []
for model_name, preds in res.items():
    print(f"\n {model_name}: predictions")
    total = len(preds)
    count_1 = sum(1 for p in preds if p==1)
    count_2 = total-count_1 
    
    model_evaded_positions = []
    model_evaded_samples = []
    
    for i, p in enumerate(preds): 
        if p == 0: 
           xtrain_position = adv_idx[i] 
           original_position = idx_train[xtrain_position]
           model_evaded_positions.append(original_position)
            
    if model_evaded_positions:
        for og_position in model_evaded_positions:
            og_sample = df.iloc[og_position]['Sample Name']
            model_evaded_samples.append(og_sample)
        evaded_samples.extend(model_evaded_samples)
        original_positions.extend(model_evaded_positions)
    else: 
        print(f"\n No samples evaded for {model_name}")
    
    print(f"\n {model_name} evasion rate: {count_2}/{total} samples evaded")
    
    sample_names = [s.rsplit('_', 1)[0] for s in model_evaded_samples]
    print("\n evaded samples: ", Counter(sample_names))

 Decision_Tree: predictions

 Decision_Tree evasion rate: 153/170 samples evaded

 evaded samples:  Counter({'None': 13, 'GandCrab': 11, 'UpdateInformation.html': 8, 'UpdateRecords.html': 7, 'Conti': 5, 'Attachment.html': 4, 'Sodinokibi': 4, 'Babuk': 3, 'Chaos': 3, 'NominatusStorm': 3, 'Azov': 3, 'UpdateNow.html': 3, 'FORM.html': 3, 'RedLineStealer': 3, 'UpdateForm.html': 2, 'njrat': 2, 'Egregor': 2, 'Snatch': 2, 'FormUpdate.html': 2, 'Update-Form618.html': 1, '4444': 1, 'Dharma': 1, 'Update425.html': 1, 'PP-Form445.html': 1, 'ESCAL': 1, 'Higuniel': 1, 'Attachment986.html': 1, 'RubberDucky': 1, 'Attachment581.html': 1, 'Jcrypt': 1, 'G0nnaC0pe': 1, 'Bobik': 1, 'FormAttachment.html': 1, 'LimeRAT': 1, 'Update442.html': 1, 'AXLocker': 1, 'Update-Form110.html': 1, 'Balaclava': 1, 'XFilesStealer': 1, 'DoejoCrypt': 1, 'Mespinoza': 1, 'Form499.html': 1, 'Phobos': 1, 'EternityStealer': 1, 'Update-Form353.html': 1, 'Exorcist': 1, 'BlackOut': 1, 'Mydoom': 1, 'Attachment934.html': 1, 'Erica': 1, 'HiddenTear': 1, 'Python': 1, 'Wannacry': 1, 'Thanos': 1, 'Form350.html': 1, 'Nitro': 1, 'CryToy': 1, 'Form953.html': 1, 'Attached.html': 1, 'Loki': 1, 'Ryuk': 1, 'LegionLocker': 1, 'Cerber': 1, 'RagnarLocker': 1, 'Update276.html': 1, 'Paradise': 1, 'Blackmoon': 1, 'MedusaLocker': 1, 'Blackcocaine': 1, 'FormAttached.html': 1, 'UpdateForm447.html': 1, 'LilithCrypt': 1, 'DarkWorld': 1, 'Mimikatz': 1, 'Maze': 1, 'UpdateForm413.html': 1, 'Kraken': 1, 'Nefilim': 1, 'AttachedForm699.html': 1, 'Spora': 1, 'PP-Form334.html': 1, 'Matrix': 1, 'DeriaLock': 1, 'VoidCrypt': 1, 'Ransomare.NominatusStrike': 1, 'QNAPCrypt': 1, 'BianLian': 1, 'HelloXD': 1, 'PP-Form430.html': 1})

 XGB: predictions

 No samples evaded for XGB

 XGB evasion rate: 0/170 samples evaded

 evaded samples:  Counter()

 SVM_poly: predictions

 No samples evaded for SVM_poly

 SVM_poly evasion rate: 0/170 samples evaded

 evaded samples:  Counter()

 SVM_Linear: predictions

 SVM_Linear evasion rate: 135/170 samples evaded

 evaded samples:  Counter({'None': 11, 'UpdateInformation.html': 8, 'UpdateRecords.html': 7, 'Attachment.html': 4, 'Hive': 4, 'RedLineStealer': 4, 'Sodinokibi': 3, 'Babuk': 3, 'Chaos': 3, 'DarkSide': 3, 'NominatusStorm': 3, 'Azov': 3, 'UpdateNow.html': 3, 'FORM.html': 3, 'Clop': 2, 'UpdateForm.html': 2, 'Mespinoza': 2, 'Conti': 2, 'Egregor': 2, 'Snatch': 2, 'FormUpdate.html': 2, 'Update-Form618.html': 1, '4444': 1, 'Update425.html': 1, 'PP-Form445.html': 1, 'Higuniel': 1, 'Attachment986.html': 1, 'BlueSky': 1, 'RubberDucky': 1, 'Attachment581.html': 1, 'Jcrypt': 1, 'G0nnaC0pe': 1, 'Bobik': 1, 'BlackBasta': 1, 'FormAttachment.html': 1, 'LimeRAT': 1, 'Update442.html': 1, 'AXLocker': 1, 'Update-Form110.html': 1, 'XFilesStealer': 1, 'Form499.html': 1, 'EternityStealer': 1, 'Update-Form353.html': 1, 'Exorcist': 1, 'MountLocker': 1, 'BlackOut': 1, 'Mydoom': 1, 'Attachment934.html': 1, 'HiddenTear': 1, 'Python': 1, 'Wannacry': 1, 'ArkeiStealer': 1, 'Thanos': 1, 'Form350.html': 1, 'Nitro': 1, 'CryToy': 1, 'Form953.html': 1, 'Attached.html': 1, 'Loki': 1, 'LegionLocker': 1, 'Cerber': 1, 'Update276.html': 1, 'Paradise': 1, 'Blackmoon': 1, 'MedusaLocker': 1, 'Blackcocaine': 1, 'FormAttached.html': 1, 'UpdateForm447.html': 1, 'LilithCrypt': 1, 'Mimikatz': 1, 'Maze': 1, 'UpdateForm413.html': 1, 'AttachedForm699.html': 1, 'PP-Form334.html': 1, 'DeriaLock': 1, 'VoidCrypt': 1, 'Ransomare.NominatusStrike': 1, 'QNAPCrypt': 1, 'BianLian': 1, 'PP-Form430.html': 1})

 Logistic_Regression: predictions

 Logistic_Regression evasion rate: 52/170 samples evaded

 evaded samples:  Counter({'None': 7, 'Babuk': 3, 'Chaos': 3, 'RedLineStealer': 3, 'Sodinokibi': 2, 'njrat': 2, '4444': 1, 'Higuniel': 1, 'RubberDucky': 1, 'Jcrypt': 1, 'Bobik': 1, 'Clop': 1, 'LimeRAT': 1, 'AXLocker': 1, 'XFilesStealer': 1, 'EternityStealer': 1, 'ransom4.bin': 1, 'Exorcist': 1, 'MountLocker': 1, 'BlackOut': 1, 'Mydoom': 1, 'Wannacry': 1, 'Thanos': 1, 'Nitro': 1, 'CryToy': 1, 'Loki': 1, 'Cerber': 1, 'Paradise': 1, 'MedusaLocker': 1, 'DarkWorld': 1, 'Mimikatz': 1, 'Kraken': 1, 'Spora': 1, 'Matrix': 1, 'Mespinoza': 1, 'DeriaLock': 1, 'VoidCrypt': 1, 'Ransomare.NominatusStrike': 1})